/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as HomeSolveIndexImport } from './routes/home/solve/index'
import { Route as HomeMyexamsIndexImport } from './routes/home/myexams/index'
import { Route as HomeAddQuestionIndexImport } from './routes/home/add-question/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRoute,
} as any)

const HomeSolveIndexRoute = HomeSolveIndexImport.update({
  id: '/home/solve/',
  path: '/home/solve/',
  getParentRoute: () => rootRoute,
} as any)

const HomeMyexamsIndexRoute = HomeMyexamsIndexImport.update({
  id: '/home/myexams/',
  path: '/home/myexams/',
  getParentRoute: () => rootRoute,
} as any)

const HomeAddQuestionIndexRoute = HomeAddQuestionIndexImport.update({
  id: '/home/add-question/',
  path: '/home/add-question/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/add-question/': {
      id: '/home/add-question/'
      path: '/home/add-question'
      fullPath: '/home/add-question'
      preLoaderRoute: typeof HomeAddQuestionIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/myexams/': {
      id: '/home/myexams/'
      path: '/home/myexams'
      fullPath: '/home/myexams'
      preLoaderRoute: typeof HomeMyexamsIndexImport
      parentRoute: typeof rootRoute
    }
    '/home/solve/': {
      id: '/home/solve/'
      path: '/home/solve'
      fullPath: '/home/solve'
      preLoaderRoute: typeof HomeSolveIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/home/add-question': typeof HomeAddQuestionIndexRoute
  '/home/myexams': typeof HomeMyexamsIndexRoute
  '/home/solve': typeof HomeSolveIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeIndexRoute
  '/home/add-question': typeof HomeAddQuestionIndexRoute
  '/home/myexams': typeof HomeMyexamsIndexRoute
  '/home/solve': typeof HomeSolveIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home/': typeof HomeIndexRoute
  '/home/add-question/': typeof HomeAddQuestionIndexRoute
  '/home/myexams/': typeof HomeMyexamsIndexRoute
  '/home/solve/': typeof HomeSolveIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/home/add-question'
    | '/home/myexams'
    | '/home/solve'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/home/add-question' | '/home/myexams' | '/home/solve'
  id:
    | '__root__'
    | '/'
    | '/home/'
    | '/home/add-question/'
    | '/home/myexams/'
    | '/home/solve/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeAddQuestionIndexRoute: typeof HomeAddQuestionIndexRoute
  HomeMyexamsIndexRoute: typeof HomeMyexamsIndexRoute
  HomeSolveIndexRoute: typeof HomeSolveIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeAddQuestionIndexRoute: HomeAddQuestionIndexRoute,
  HomeMyexamsIndexRoute: HomeMyexamsIndexRoute,
  HomeSolveIndexRoute: HomeSolveIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home/",
        "/home/add-question/",
        "/home/myexams/",
        "/home/solve/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/home/add-question/": {
      "filePath": "home/add-question/index.tsx"
    },
    "/home/myexams/": {
      "filePath": "home/myexams/index.tsx"
    },
    "/home/solve/": {
      "filePath": "home/solve/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
